name: Build
'on':
  - push
  - pull_request
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcairo2-dev pkg-config python3-dev
      - name: Install Python dependencies
        working-directory: notebooks
        run: |
          pip install -r requirements-build.txt
          pip install -r requirements-check.txt
      - name: Install PyTorch (CPU only version)
        working-directory: notebooks
        run: >-
          pip install "torch>=2,<3" --index-url https://download.pytorch.org/whl/cpu
      - name: 'Widgets: Install dependencies'
        working-directory: widgets
        run: npm i
      - name: 'Widget wrappers: Install dependencies'
        working-directory: notebooks/widget-wrappers
        run: npm i
      - name: Run checks
        working-directory: scripts
        run: ./checkall.sh

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcairo2-dev pkg-config python3-dev
      - name: Install Python dependencies
        working-directory: notebooks
        run: pip install -r requirements-build.txt
      - name: Install PyTorch (CPU only version)
        working-directory: notebooks
        run: >-
          pip install "torch>=2,<3" --index-url https://download.pytorch.org/whl/cpu
      - name: Trust the notebooks
        working-directory: notebooks
        run: jupyter trust vae.ipynb
      - name: Run the notebook
        working-directory: notebooks
        run: jupyter execute vae.ipynb --output=vae.out.ipynb
