name: Build

on: [push, pull_request]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Python dependencies
        working-directory: notebook
        run: pip install -r requirements-build.txt

      - name: Trust the notebook
        working-directory: notebook
        run: jupyter trust notebook.ipynb

      - name: Run the notebook
        working-directory: notebook
        run: jupyter execute notebook.ipynb --output=notebook.out.ipynb
